### PR TITLE
fix: prevent internal server error when user is null

### LINKED ISSUE #101: Bug: getComments feiler når comment.user er null

### PR DESCRIPTION
**Pull request by jeffreiffers**
Fixes #101

### CODE REVIEW

File: src/main/kotlin/no/digdir/catalog_comments_service/service/CommentService.kt [hunk 1]
```diff
@@ -35,28 +35,26 @@ class CommentService (private val commentDAO: CommentDAO, private val userDAO: U
...
-                comment = obj.comment ?: ""
-            )
-            ?.updateLastChanged()
-            ?.let { commentDAO.save(it) }
-            ?.let { it.toDTO(userDAO.findById(userId)) }
+                ?.copy(
+                    comment = obj.comment ?: ""
+                )
+                ?.updateLastChanged()
+                ?.let { commentDAO.save(it) }?.toDTO(userDAO.findByIdOrNull(userId))
```
Comment (NilsOveTen) [inline src/main/kotlin/no/digdir/catalog_comments_service/service/CommentService.kt:57]:
```suggestion
            ?.copy(comment = obj.comment ?: "")
            ?.updateLastChanged()
            ?.let { commentDAO.save(it) }?.toDTO(userDAO.findByIdOrNull(userId))
```

**Review by NilsOveTen — APPROVED** [review]
